### PR TITLE
Fix/darkmode accounts

### LINKED ISSUE #2234: Website 🐛 [Bug]: Accounts make transparent background
### Description
image
image
image
image
image
image
image
image
image
image
image

### To Reproduce

_No response_

### Current vs. Expected behavior

_No response_

### Which area(s) are affected? (Select all that apply)

_No response_

### Additional context

_No response_

### LINKED ISSUE #2242: Website 🐛 [Bug]: Accounts Tab in mobile version not selecting correct tab
### Description

Sample bug issue

[screencast-test.zesty.io_3000-2024.01.02-20_17_02.webm](https://github.com/zesty-io/website/assets/44116036/ed15407c-a643-4543-aec0-b9bdaf80f871)

### To Reproduce

_No response_

### Current vs. Expected behavior

_No response_

### Which area(s) are affected? (Select all that apply)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by glespinosa**
image
image
image
image
image
image
image

### CODE REVIEW

File: src/components/accounts/instances/InstancesApp.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const Index = ({ children }) => {
     location?.pathname?.split('/').length > 2
       ? location?.pathname?.split('/')[3]
       : '';
-  const [tabValue, setTabValue] = useState(currentPage);
+  const [, setTabValue] = useState(currentPage);
```
Comment (darwin808) [inline src/components/accounts/instances/InstancesApp.js:39]: where is this use?

**Review by darwin808 — CHANGES_REQUESTED** [review]
image
image
image

File: src/components/accounts/instances/InstancesApp.js (hunk 1 above)
Comment (glespinosa) [reply src/components/accounts/instances/InstancesApp.js:39]: 1 I'll fix that issue in modal 
image

2 issue: in the accounts tab in Mobile. I removed the tabValue since its not being used since currentPage is enough to tell where the current tab is selected
image

Comment (glespinosa) [reply src/components/accounts/instances/InstancesApp.js:39]: @darwin808 this will fix the issue in the number 1 
https://github.com/zesty-io/website/pull/2249/commits/dbdd62c4c29b0d2144070f5035d6903c6119f1a9

Comment (darwin808) [reply src/components/accounts/instances/InstancesApp.js:39]: image

Comment (glespinosa) [reply src/components/accounts/instances/InstancesApp.js:39]: image

Comment (darwin808) [reply src/components/accounts/instances/InstancesApp.js:39]: image

**Review by darwin808 — APPROVED** [review]
