### PR TITLE
Fix: login delay and update next `14.0.4` 

### LINKED ISSUE #2220: Page redirect to /login has a delay (unauthenticated user)
Steps:

1. user logs in dev environment (https://auth.api.dev.zesty.io/google/login)
2. once user successfully logs in, page is redirected to https://zesty.io
3. the page will then be redirected to https://zesty.io/login after a few seconds which has a bit of delay

See the first video attached in https://github.com/zesty-io/website/issues/2169#issue-2020850983 as example.

### PR DESCRIPTION
**Pull request by darwin808**
# Description

- This will fix the login delay when logging in from dev 
- update next js version to `14.0.4`

Fixes #2220 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- [x] Manual Test
- [ ] Unit Test
- [ ] E2E Test

### CODE REVIEW

File: src/views/zesty/Homepage/index.js [hunk 1]
```diff
@@ -82,6 +83,13 @@ const GetDemoSection = dynamic(() => import('./GetDemoSection'), {
 function Homepage({ content }) {
   const { palette } = useTheme();
   const isLoggedIn = useIsLoggedIn();
+  const zestyProductionMode = getCookie('PRODUCTION');
+
+  useEffect(() => {
+    if (!zestyProductionMode) {
+      setCookie('PRODUCTION', content?.zestyProductionMode);
```
Comment (mattezra) [inline src/views/zesty/Homepage/index.js:90]: What is the purpose of setting another cookie here? Looks like this can be derived from the page URL already.
