### PR TITLE
Accounts fixes in Settings/Domain tab 

### LINKED ISSUE #1120: added domains to an instance do not target blank and links do not functions
after adding a live or dev domain to an instance, clicking the link provided does not to a target blank and open a new tab for the domain.  The domain also does not display the domain content - it looks to automatically append `www` without checking that the `www` prepend setting is active.

the domains work as expected in legacy accounts

Image

Image

### LINKED ISSUE #1121: Configured Domain settings doesn't take effect
@dj-gaban-zestyio : transferring ticket to website repo for accounts

**Describe the bug**
Domain setting changes are seen in the content manager as update but are not reflected when a user clicks on the domain to view in beta. the domain settings need to be pulled first to format the domains listed on domain page

**To Reproduce**
1. Go to any instance/s
2. Change/Configure all domain settings -> Hit "Save"
image

3. Add/create domain
image

4. Hover/Click onto the recently created domain -> See domain settings didn't apply
image
image

**Expected behavior**
Domain setting changes should be reflected in instance/s domain output

### LINKED ISSUE #1128: Instance Settings: use Capital first letter on category name
Use label value of category rather than reference name in the category dropdown

Image

### LINKED ISSUE #1130: Clicking Export Template needs loading icon
When a user clicks Export Template (in Settings view) there is no UI response to let them know that their download is occurring. Please add a loading icon to let the user know of the action. 

Image

### LINKED ISSUE #1132: Unable to make selection or change WebEngine Mode setting
Dropdown menu for WebEngine Mode in settings does not have a selection option -Stef

Loom: https://www.loom.com/share/cbe1548fadfb440494406e7e83ab611b

I am able to save but it's not reflecting on instance - Gisele

Loom: https://www.loom.com/share/02a66b86b08849f4b2c3db04f5e97294

### PR DESCRIPTION
**Pull request by darwin808**
## Settings Tab

image
image

### CODE REVIEW

File: src/utils/index.js [hunk 1]
```diff
@@ -188,6 +188,7 @@ export const generateUniqDropdown = ({ data, property = 'category' }) => {
         ),
     );
   const res = [{ value: '', label: 'All Categories' }, ...dropdownList];
+  console.log(data, '44::');
```
Comment (ardeay) [inline src/utils/index.js]: Remove

File: src/views/accounts/instances/Settings.js [hunk 2]
```diff
@@ -48,6 +50,12 @@ const ActionSwitcher = ({ data, setarrToSubmit, arrToSubmit }) => {
     setarrToSubmit([...arrToSubmit, data]);
   };
 
+  const selectOptions = OPTIONS(options, ';')?.map((e) => {
+    const value = e.value.split(':')[0];
+    const label = e.label.split(':')[1];
+    return { value, label };
+  });
+  console.log(selectOptions, '8888');
```
Comment (ardeay) [inline src/views/accounts/instances/Settings.js]: Remove

**Review by ardeay — CHANGES_REQUESTED** [review]
