### PR TITLE
fix: update experience when installing module if not logged in

### LINKED ISSUE #1543: Marketplace: install button should be disabled if logged out
If the user is logged out, the install button for marketplace apps, modules, etc should be disabled and prompt the user to login to install the item.

### PR DESCRIPTION
**Pull request by allenpigar**
add login button if user is not logged in when installing module.

image

### CODE REVIEW

File: src/components/marketplace/ExtensionsIntaller.js [hunk 1]
```diff
@@ -29,8 +49,16 @@ const ExtensionsIntaller = ({ extensionName, githubUrl }) => {
   const getInstanceSchema = async () => {
     const res = await ZestyAPI.getModels();
     var obj = { 0: 'Root' };
```
Comment (darwin808) [inline src/components/marketplace/ExtensionsIntaller.js]: can we change the `var` to `const` / `let` cause were using es6

**Review by darwin808 — CHANGES_REQUESTED** [review]

File: src/components/marketplace/ExtensionsIntaller.js (hunk 1 above)
Comment (allenpigar) [reply src/components/marketplace/ExtensionsIntaller.js]: done updating variables.
