### PR TITLE
fix(appnavigation): bug no data accounts dropdown in navigation (#1332)

### LINKED ISSUE #1332: Bug no data accounts dropdown in navigation
image

### PR DESCRIPTION
**Pull request by darwin808**
image

### CODE REVIEW

File: src/layouts/Main/components/AppNavigation/AppNavigation.js [hunk 1]
```diff
@@ -145,6 +151,11 @@ const AppNavigation = ({
     setIsToggle(false);
   }, [isMD]);
 
+  useEffect(() => {
```
Comment (glespinosa) [inline src/layouts/Main/components/AppNavigation/AppNavigation.js:152]: @darwin808 I think we don't need the additional isLoggedIn condition because the <AppNavigation/> is already wrapped in isLoggedIn in Main.js and also other conditions in line `219` and `252` that depends on isLoggedIn. Please check if it will cause unusual behavior. Thanks

**Review by glespinosa — CHANGES_REQUESTED** [review]

**Review by glespinosa — APPROVED** [review]

**Review by ardeay — APPROVED** [review]
