### PR TITLE
fix(middleware,cookies,login,2fa,refactor): middleware,cookies,login,…

### LINKED ISSUE #1000: Dashboard view should only load if user is logged in

### LINKED ISSUE #1001: Login button should go to /login

### LINKED ISSUE #1005: Debug login flow
Looks like the login hangs or it possibly tries to get all instances when not logged in

### PR DESCRIPTION
**Pull request by glespinosa**
- Show more button will show only when instances > 5 and when click it will let you through to /instances
- Individual Instances have now links
- correct way of getting isAuthenticated in the response.getHeader instead to the request.
- Resolved the bug in two factor authorization
- set login path to /login

#### Note: To test if the middleware is functioning correctly, try logging in then delete manually the DEV_APP_SID / APP_SID then try going to different pages if it behaves correctly

image

### CODE REVIEW

**Review by ardeay — APPROVED** [review]

File: src/components/console/AppBar.js [hunk 1]
```diff
@@ -129,7 +129,7 @@ export default function AppBar({ url = window.location.pathname }) {
             <Box>
               {!verifySuccess ? (
                 <Button
-                  href={`https://accounts.zesty.io/login`}
+                  href="/login"
```
Comment (ardeay) [inline src/components/console/AppBar.js:132]: change to `/login/`

File: src/layouts/Main/components/Topbar/Topbar.js [hunk 2]
```diff
@@ -139,7 +139,7 @@ const Topbar = ({
                     endIcon={<LoginIcon />}
                     fullWidth
                     component="a"
-                    href="https://accounts.zesty.io"
+                    href="/login"
```
Comment (ardeay) [inline src/layouts/Main/components/Topbar/Topbar.js:142]: switching `/login/`
