### PR TITLE
Fix/instances view

### LINKED ISSUE #955: Include "Create Instance" in the instances nav

### LINKED ISSUE #956: Instances grid view show 6 across when wide

### PR DESCRIPTION
**Pull request by darwin808**
image
image
image
image
image

### CODE REVIEW

File: src/components/accounts/instances/LaunchInstance.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+      variant="p"
+      sx={{ whiteSpace: 'nowrap', display: 'flex', alignItems: 'center' }}
+    >
+      <AddIcon /> Create Instance
+    </Typography>
+  ),
+  onClick,
+}) => {
+  const handleClick = () => {
+    onClick();
```
Comment (ardeay) [inline src/components/accounts/instances/LaunchInstance.js:17]: Where does this go?

Comment (darwin808) [reply src/components/accounts/instances/LaunchInstance.js:17]: https://accounts.zesty.io/instances/create
