### PR TITLE
fix: login meta title and description issue

### LINKED ISSUE #2416: #website Meta title and Meta Description error for the Login page
Incorrectly shows information from the instance 
Shows:

Image

Should show the Meta title and Meta description in SEO:

Image

### PR DESCRIPTION
**Pull request by japhethLG**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2416

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] Manual Test

# Screenshots / Screen recording

Please add screenshots or recording if applicable
image

**fixed**
image

### CODE REVIEW

File: src/pages/login/index.js [hunk 1]
```diff
@@ -69,19 +70,25 @@ export async function getServerSideProps({ req, res }) {
   const isProd = process.env.PRODUCTION === 'true' ? true : false;
 
   let url = 'https://www.zesty.io/-/instant/6-90fbdcadfc-4lc0s5.json';
+  let loginUrl = 'https://www.zesty.io/-/instant/6-ccb9ca9fc1-06fhhc.json';
```
Comment (darwin808) [inline src/pages/login/index.js]: can you simplify this?

Comment (japhethLG) [reply src/pages/login/index.js]: @darwin808 got it, changed the logic a bit

**Review by darwin808 — APPROVED** [review]
