### PR TITLE
Fix/accounts gtm chat

### LINKED ISSUE #1124: If a user is detected, dont show this popup
image

### PR DESCRIPTION
**Pull request by glespinosa**
When logged in gtm chat should not show
image
image

### CODE REVIEW

File: src/pages/_document.js [hunk 1]
```diff
@@ -28,10 +34,42 @@ export default class MyDocument extends Document {
...
+              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
+              })(window,document,'script','dataLayer','${GTM_ID}');
+          `,
+              }}
+            />
+          )}
         </Head>
         <body>
           <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
+          <noscript>
```
Comment (ardeay) [inline src/pages/_document.js]: the tag manager script and zoom info script should also NOT load when logged in.

**Review by ardeay — CHANGES_REQUESTED** [review]

**Review by ardeay — APPROVED** [review]
